Updated contact.html for validation of Number field
NJACKWinterOfCode/Physics-quiz pull request #24
Opened 2019-12-05 19:05 UTC by sakshamj74

2019-12-05 19:19 UTC, rajat2502 requested changes

2019-12-05 19:19 UTC, rajat2502 commented on contact.html
> +                                        	<input type="text" name="phone" pattern="[6-9]{1}[0-9]{9}" value="" placeholder="Phone"title="Phone number with 7-9 and remaing 9 digit with 0-9" required>
the title should be a valid phone number starting from 6-9 and rest of the digits from0-9
Also, give space between placeholder and title attribute.

2019-12-05 19:32 UTC, sakshamj74 commented
@rajat2502 Please review.

2019-12-06 15:33 UTC, rajat2502 approved these changes

2019-12-06 15:34 UTC, rajat2502 commented
Thanks!!!

2019-12-06 15:34 UTC, merged